version: "2"
services:
  node:
    build: .
    network_mode: bridge
    env_file: ./env
    ports:
      - 3333:3333
    links:
      - db
    volumes:
      - /src
      - ./src:/src

  db:
    image: mysql:5.7.22
    network_mode: bridge
    command: ["--max_allowed_packet=512M", "--character-set-server=utf8"]
    ports:
      - 3334:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:
