version: '3'

services:
  node:
    build: .
    container_name: blueprint_node
    env_file: ./env

    ports:
      - 3333:3333
    volumes:
      - ./src:/src
    depends_on:
      - db
    networks:
      general:
        aliases:
          - blueprint_node

  db:
    image: mysql:5.7.22
    container_name: blueprint_db
    command: ["--max_allowed_packet=512M", "--character-set-server=utf8"]

    ports:
      - 3334:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=adonis
    networks:
      general:
        aliases:
          - blueprint_db

networks:
  general:
    external: true